[package]
name = "aoc-day-8"
authors = ["Paul Zhang <me@paul-zhang.de>"]
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-2023-common = { path = "../common" }

eyre = "0.6.9"
itertools = "0.12.0"
regex = "1.10.2"
once_cell = "1.19.0"
num = "0.4.1"